[tool.poetry]
name = "groza_statistics"
version = "0.0.1"
description = "statistics on dayz server app"
authors = ["Yzoop"]

[tool.poetry.dependencies]
python = "3.11.6"
plotly = "^5.18.0"
pandas = "^2.1.2"
streamlit = "^1.28.0"